apiVersion: apps/v1
kind: Deployment
metadata:
  name: comms-api
spec:
  selector:
    matchLabels:
      app: comms
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: comms
        version: v1
    spec:
      containers:
        - name: comms-container
          image: iamrobert/sc-api-comms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: EmailSettings__WebUrl
              value: "https://snowcapture.com"
            - name: EmailSettings__Name
              value: "Snow Capture"
            - name: EmailSettings__EmailAddress
              value: "noreply@snowcapture.com"
            - name: EmailSettings__Host
              value: "mailhog"
            - name: EmailSettings__Port
              value: "1025"
            - name: ConnectionStrings__Database
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: COMMS_CONNECTION_STRING
            - name: ConnectionStrings__Redis
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: REDIS_CONNECTION_STRING
            - name: Shared__ReCaptchaSecretKey
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: ReCaptchaSecretKey
            - name: Shared__JwtIssuerKey
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: JwtIssuerKey
            - name: RabbitMq__Hostname
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: RABBITMQ_HOSTNAME
            - name: RabbitMq__Username
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: RABBITMQ_USERNAME
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: RABBITMQ_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: comms-api
  labels:
    app: comms
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: comms
