apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
spec:
  selector:
    matchLabels:
      app: identity
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: identity
        version: v1
    spec:
      containers:
        - name: identity-container
          image: iamrobert/sc-api-identity:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__Database
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: IDENTITY_CONNECTION_STRING
            - name: ConnectionStrings__Redis
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: REDIS_CONNECTION_STRING
            - name: Shared_ReCaptchaSecretKey
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: ReCaptchaSecretKey
            - name: Shared__JwtIssuerKey
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: JwtIssuerKey
            - name: RabbitMq__Hostname
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: RABBITMQ_HOSTNAME
            - name: RabbitMq__Username
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: RABBITMQ_USERNAME
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: RABBITMQ_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: identity-api
  labels:
    app: identity
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: identity
