apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
spec:
  selector:
    matchLabels:
      app: web-ui
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: web-ui
        version: v1
    spec:
      containers:
        - name: web-ui-container
          image: iamrobert/sc-ui-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui
  labels:
    app: web-ui
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: web-ui
