name: Web Angular Docker

on:
  push:
    branches: [main]
    paths:
      - 'Frontend/Angular/Desktop/**.ts'
      - 'Frontend/Angular/Desktop/Dockerfile'
      - 'Frontend/Angular/Desktop/angular.json'
      - 'Frontend/Angular/Shared/**.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.5.0

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./Frontend/Angular
          file: ./Frontend/Angular/Desktop/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/project-infinite-ui-ng:latest
          push: true
          build-args: |
            FONTAWESOME_NPM_AUTH_TOKEN=${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
