name: Gateway .NET CI

on:
  push:
    branches: [ master ]
    paths:
    - 'snow-capture/backend/gateway/**.cs'
    - 'snow-capture/backend/gateway/**.csproj'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
      working-directory: backend/gateway
    - name: Build
      run: dotnet build --no-restore
      working-directory: backend/gateway
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: backend/gateway
