name: Identity Docker

on:
  push:
    branches: [main]
    paths:
      - "./Backend/Microservices/Identity/**.cs"
      - "./Backend/Microservices/Identity/**.csproj"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./Backend
          file: ./Backend/Microservices/Identity/Identity.Api/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/sc-api-identity:latest
          push: true
