name: Sockets Docker

on:
  push:
    branches: [main]
    paths:
      - 'Backend/Shared/Libraries/**.cs'
      - 'Backend/Microservices/Sockets/**.cs'
      - 'Backend/Microservices/Sockets/**.csproj'
      - 'Backend/Microservices/Sockets/Sockets/Dockerfile'
      - 'Backend/Microservices/Sockets/Sockets/appsettings.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.5.0

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./Backend
          file: ./Backend/Microservices/Sockets/Sockets/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/project-infinite-api-sockets:latest
          push: true
