name: UI Web Docker

on:
  push:
    branches: [main]
    paths:
      - "Frontend/Desktop/**.ts"
      - "Frontend/Desktop/nginx-custom.conf"
      - "Frontend/Desktop/Dockerfile"
      - "Frontend/Desktop/angular.json"
      - "Frontend/Shared/**.ts"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.5.0

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./Frontend
          file: ./Frontend/Desktop/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/sc-ui-web:latest
          push: true
          build-args: |
            FONTAWESOME_NPM_AUTH_TOKEN=${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
